// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace TwoPlayersOnly
{
public static class GPGS
{
        public const string achievement_fast_champ = "CgkIqeb0_poSEAIQAg"; // <GPGSID>
        public const string achievement_2_player_master = "CgkIqeb0_poSEAIQDQ"; // <GPGSID>
        public const string achievement_legend = "CgkIqeb0_poSEAIQCw"; // <GPGSID>
        public const string achievement_pinponger = "CgkIqeb0_poSEAIQDg"; // <GPGSID>
        public const string achievement_ninjevader = "CgkIqeb0_poSEAIQDw"; // <GPGSID>
        public const string achievement_fast_master = "CgkIqeb0_poSEAIQBg"; // <GPGSID>
        public const string achievement_super_crazy_fast_master = "CgkIqeb0_poSEAIQCA"; // <GPGSID>
        public const string achievement_supporter = "CgkIqeb0_poSEAIQEA"; // <GPGSID>
        public const string achievement_medium_master = "CgkIqeb0_poSEAIQBQ"; // <GPGSID>
        public const string achievement_super_fast_champ = "CgkIqeb0_poSEAIQAw"; // <GPGSID>
        public const string achievement_2_player_champ = "CgkIqeb0_poSEAIQDA"; // <GPGSID>
        public const string achievement_rookie = "CgkIqeb0_poSEAIQCQ"; // <GPGSID>
        public const string achievement_veteran = "CgkIqeb0_poSEAIQCg"; // <GPGSID>
        public const string achievement_super_crazy_fast_champ = "CgkIqeb0_poSEAIQBA"; // <GPGSID>
        public const string achievement_super_fast_master = "CgkIqeb0_poSEAIQBw"; // <GPGSID>
        public const string achievement_medium_champ = "CgkIqeb0_poSEAIQAQ"; // <GPGSID>

}
}
